spring:
  application:
    name: service-movements #(1)
  cloud:
    config:
      profile: dev #(3) dev, qa, prod
  config:
    import: optional:configserver:http://localhost:8086 #(4)    
# 1.- Aqui se puede definir un nombre para la aplicacion, el cual reemplazará al 
#     definido en el pom.xml.
#
# 2.- Profile que se desee cargar desde la carpeta resources. Este atributo 
#     no es obligatorio.
#
# 3.- Define el perfil a recuperar desde el configserver. Lo ideal es que 
#     este valor sea especificado de forma externa p. ej. por linea de 
#     comandos al iniciar el ms.
#
# 4.- Esta es la nueva forma de configurar el acceso al configserver
#     a partir de la version 2.4.x de springboot. El atributo optional
#     indica que si el ms no puede contactar al configserver, no dará
#     un error y continuara con la carga del servicio.